### ISSUE TITLE
Problem with angle backets in subtitles

### ISSUE THREAD

**Issue by edrx** [t4skmanag3r/youtube_transcript_downloader#1]
Hi! I am the author of this thing here,

http://anggtwu.net/find-yttranscript-links.html

that uses youtube_transcript_downloader in a REPL, and I've just discovered that in some cases y_t_d handles angle brackets incorrectly. Here's an example. In this video, at 0:14,

http://www.youtube.com/watch?v=qM0Luz78qGw#t=0m14s

the subtitles have an "f8" between angle brackets, and if we run this,
```
import youtube_transcript_downloader
url    = "http://www.youtube.com/watch?v=qM0Luz78qGw"
f      = "find-{c}video"
tr     = youtube_transcript_downloader.get_transcript(url)
trits0 = tr.items()
trits1 = '\n'.join((key + ' ' + text for key, text in trits0))
print(trits1)
```
the line at 0:14 becomes this:
```
00:14 and if we type  several times
```
The `<f8>` disappears... is that something easy to fix?

**Comment by t4skmanag3r** [comment]
that's odd, the transcript from the video track is different from the one you get from their API (you can see it by clicking ... -> show transcript, under the video). I don't think I can really do anything since it's on their side.
